language: node_js
node_js:
  - "0.10"
after_script: "node ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -u exports -R spec && npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"